apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T10:17:48Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "4829"
  uid: c7d3f425-bb89-4e91-a124-e8f2c5a7b93d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.142.203 
  clusterIPs:
  - 10.98.142.203 
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32847
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}